In [1]:
import numpy as np
import pandas as pd

In [98]:
# Question 1

In [99]:
np.version.version

'1.20.3'

In [ ]:
# Question 2

In [2]:
data_cars= pd.read_csv("data.csv")

In [4]:
len(data_cars)

11914

In [5]:
data_cars

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [ ]:
# Question 3

In [6]:
data_cars['Make'].value_counts()[:3].index.tolist()

['Chevrolet', 'Ford', 'Volkswagen']

In [ ]:
# Question 4

In [13]:
data_cars[data_cars["Make"]== "Audi"]["Model"].nunique()

34

In [ ]:
# Question 5

In [24]:
data_cars.isnull().any(axis=0).sum()

5

In [ ]:
# Question 6

In [61]:
data_cars["Engine Cylinders"].median()

6.0

In [65]:
most_frecuent=data_cars["Engine Cylinders"].value_counts().index.tolist()[0]
most_frecuent


4.0

In [57]:
data_cars_clean=data_cars.copy()
data_cars_clean["Engine Cylinders"].fillna(most_frecuent, inplace = True)

In [58]:
data_cars_clean["Engine Cylinders"].value_counts()

4.0     4782
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [59]:
data_cars_clean["Engine Cylinders"].median()

6.0

In [ ]:
# Question 7

In [70]:
data_reggresion=data_cars.copy()
data_reggresion=data_reggresion[data_reggresion["Make"] == "Lotus"][["Engine HP", "Engine Cylinders"]].drop_duplicates()
data_reggresion

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3918      217.0               4.0
4216      350.0               8.0
4257      400.0               6.0
4259      276.0               6.0
4262      345.0               6.0
4292      257.0               4.0
4293      240.0               4.0

In [88]:
X =data_reggresion.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [89]:
XTX = np.matmul(np.transpose(X),X)

In [90]:
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [91]:
inverseXTX=np.linalg.inv(XTX) 

In [92]:
inverseXTX

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [93]:
y = [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800]

In [94]:
inverseXTXdotXT=np.matmul(inverseXTX,np.transpose(X))

In [95]:
inverseXTXdotXT

array([[-1.31950096e-03,  2.84443321e-04,  2.29134897e-04,
        -4.18763778e-03,  4.46417989e-03, -2.39406462e-03,
         1.42221660e-03,  2.44147184e-03,  1.50122864e-03],
       [ 8.60893170e-02,  7.36567735e-04,  3.67976598e-03,
         2.54588185e-01, -2.13748621e-01,  1.51207962e-01,
        -5.18727169e-02, -1.14048164e-01, -6.40137937e-02]])

In [96]:
W=np.matmul(inverseXTXdotXT,y)

In [97]:
W

array([  4.59494481, -63.56432501])